import * as T from 'three';
import { EffectComposer } from 'three/addons/postprocessing/EffectComposer.js';
import { RenderPass } from 'three/addons/postprocessing/RenderPass.js';
import { ShaderPass } from 'three/addons/postprocessing/ShaderPass.js';
import { OutputPass } from 'three/addons/postprocessing/OutputPass.js';
import { UnrealBloomPass } from 'three/addons/postprocessing/UnrealBloomPass.js';
import { FXAAShader } from 'three/addons/shaders/FXAAShader.js';
import { SSAOPass } from 'three/addons/postprocessing/SSAOPass.js';
import { RoomEnvironment } from 'three/addons/environments/RoomEnvironment.js';
import { createWorld, height, U, homes } from './world.js';
import './style.css';
const $=s=>document.querySelector(s),canvas=$('#world');
let renderer;
try{renderer=new T.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance',alpha:false});}catch(e){$('#webgl-error').hidden=false;$('#loading').style.display='none';throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.setSize(innerWidth,innerHeight);renderer.info.autoReset=false;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.14;
const scene=new T.Scene();scene.background=new T.Color('#afc6bb');scene.fog=new T.FogExp2('#b9caba',.0044);
const camera=new T.PerspectiveCamera(47,innerWidth/innerHeight,.15,650);camera.rotation.order='YXZ';camera.position.set(46,24,52);camera.lookAt(-6,10,-15);let yaw=camera.rotation.y,pitch=camera.rotation.x;
const hemi=new T.HemisphereLight('#d4ebef','#667153',2.05);scene.add(hemi);const sun=new T.DirectionalLight('#fff0cb',3.25);sun.position.set(-45,72,35);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-85;sun.shadow.camera.right=85;sun.shadow.camera.top=80;sun.shadow.camera.bottom=-80;sun.shadow.camera.near=1;sun.shadow.camera.far=210;sun.shadow.normalBias=.035;sun.shadow.bias=-.00017;sun.shadow.radius=2;sun.target.position.set(-5,0,-14);scene.add(sun,sun.target);const fill=new T.DirectionalLight('#bddeec',.32);fill.position.set(40,20,-35);scene.add(fill);
const env=new T.PMREMGenerator(renderer);const room=new RoomEnvironment();scene.environment=env.fromScene(room,.04).texture;scene.environmentIntensity=.24;room.dispose();env.dispose();
const world=createWorld(scene);
const composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));
const ao=new SSAOPass(scene,camera,Math.round(innerWidth*.6),Math.round(innerHeight*.6));ao.kernelRadius=1.8;ao.minDistance=.0003;ao.maxDistance=.012;ao.enabled=false;
// Cutout leaf cards must not become opaque rectangles in the normal prepass.
const aoExcluded=[];scene.traverse(o=>{if(o.isMesh&&(o.material?.alphaTest>0||o.userData.noAO))aoExcluded.push(o);});const renderAO=ao.render.bind(ao);ao.render=(...args)=>{const visibility=aoExcluded.map(o=>o.visible);const {autoUpdate,needsUpdate}=renderer.shadowMap;aoExcluded.forEach(o=>o.visible=false);renderer.shadowMap.autoUpdate=false;renderer.shadowMap.needsUpdate=false;try{return renderAO(...args);}finally{aoExcluded.forEach((o,i)=>o.visible=visibility[i]);renderer.shadowMap.autoUpdate=autoUpdate;renderer.shadowMap.needsUpdate=needsUpdate;}};
composer.addPass(ao);
const bloom=new UnrealBloomPass(new T.Vector2(innerWidth,innerHeight),.19,.65,1.03);bloom.enabled=false;composer.addPass(bloom);composer.addPass(new OutputPass());
const grade=new ShaderPass({uniforms:{tDiffuse:{value:null},resolution:{value:new T.Vector2(innerWidth,innerHeight)},mode:U.mode,time:U.time},vertexShader:`varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`,fragmentShader:`uniform sampler2D tDiffuse;uniform vec2 resolution;uniform float mode;uniform float time;varying vec2 vUv;
float lum(vec3 c){return dot(c,vec3(.299,.587,.114));}float hash(vec2 p){return fract(sin(dot(p,vec2(12.9898,78.233)))*43758.5453);}
void main(){vec2 uv=vUv,px=1./resolution;vec3 col=texture2D(tDiffuse,uv).rgb;
if(mode>.5&&mode<3.5){float radius=mode>2.5?1.65:mode>1.5?.75:.65;vec3 r=texture2D(tDiffuse,uv+vec2(px.x*radius,0)).rgb;vec3 l=texture2D(tDiffuse,uv-vec2(px.x*radius,0)).rgb;vec3 t=texture2D(tDiffuse,uv+vec2(0,px.y*radius)).rgb;vec3 b=texture2D(tDiffuse,uv-vec2(0,px.y*radius)).rgb;float edge=length(r-l)+length(t-b);float line=smoothstep(mode>2.5?.28:.22,mode>2.5?.68:.60,edge);col=mix(col,mode>2.5?vec3(.10,.15,.14):vec3(.16,.21,.25),line*(mode>2.5?.60:mode>1.5?.27:.18));
if(mode<1.5){float grain=hash(floor(uv*resolution*.6))-.5;col+=grain*.012;col=mix(vec3(lum(col)),col,1.08);col=pow(max(col,vec3(0.)),vec3(1.025,.99,.98));}
}
if(mode>3.5){vec2 q=uv-.5;float halo=pow(max(0.,1.-length((uv-vec2(.15,.86))*vec2(.9,1.4))),6.);col+=vec3(.045,.028,.009)*halo;col=mix(vec3(lum(col)),col,1.055);col=pow(col,vec3(1.015,1.025,1.04));}
float vignette=1.-.16*pow(length((uv-.5)*vec2(1.,.82))*1.35,2.);col*=vignette;gl_FragColor=vec4(col,1.);}`});grade.uniforms.mode=U.mode;grade.uniforms.time=U.time;composer.addPass(grade);
const fxaa=new ShaderPass(FXAAShader);composer.addPass(fxaa);
let mode=0,exploring=false,tour=null,hidden=false;let toastTimer;
const modeNames=['Natural','Painterly','Anime','Cartoon','Ultra'];const modeCopy=['Soft sunlight · natural materials','Painted shadows · brushwork · textured edges','Cel shading · clear skies · fine outlines','Bold contours · simplified light · vivid color','Ambient occlusion · cinematic bloom · fine shadows'];
function setMode(n,toast=true){mode=n;U.mode.value=n;document.querySelectorAll('[data-mode]').forEach(b=>{const active=+b.dataset.mode===n;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});ao.enabled=n===4;bloom.enabled=n===4||n===1;bloom.strength=n===4?.2:.1;bloom.threshold=n===4?1.05:1.15;renderer.toneMappingExposure=[.98,1.02,1.03,1.02,.96][n];hemi.intensity=[.95,.80,1.10,1.20,.82][n];sun.intensity=[2.9,3.1,2.85,2.7,3.2][n];scene.fog.color.set(['#bacbd0','#a9b8c2','#b8d9e0','#bddbe1','#b3c7cf'][n]);scene.fog.density=[.0030,.0038,.0030,.0032,.0029][n];sun.color.set(n===1?'#ffdcab':'#fff0cb');scene.environmentIntensity=n===4?.38:.24;if(toast){$('#mode-toast').textContent=`${modeNames[n]} — ${modeCopy[n]}`;$('#mode-toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#mode-toast').classList.remove('visible'),2400);}}
document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>setMode(+b.dataset.mode)));
function enter(){exploring=true;$('#app').classList.add('exploring');$('#travel-state').textContent='EXPLORING';}
function reset(){tour=null;camera.position.set(46,24,52);camera.lookAt(-6,10,-15);yaw=camera.rotation.y;pitch=camera.rotation.x;velocity.set(0,0,0);exploring=false;$('#app').classList.remove('exploring');$('#travel-state').textContent='OVERLOOK';}
$('#explore').addEventListener('click',()=>{enter();tour={from:camera.position.clone(),to:new T.Vector3(3.8,4.4,26),yaw0:yaw,pitch0:pitch,t:0};const temp=new T.PerspectiveCamera();temp.rotation.order='YXZ';temp.position.copy(tour.to);temp.lookAt(-12,4,-16);tour.yaw1=temp.rotation.y;tour.pitch1=temp.rotation.x;});$('#home').addEventListener('click',reset);
$('#help').addEventListener('click',()=>$('#help-panel').hidden=!$('#help-panel').hidden);$('#close-help').addEventListener('click',()=>$('#help-panel').hidden=true);$('#fullscreen').addEventListener('click',()=>{if(document.fullscreenElement)document.exitFullscreen();else $('#app').requestFullscreen?.().catch(()=>{});});
const keys=new Set();addEventListener('keydown',e=>{if(/^[1-5]$/.test(e.key))setMode(+e.key-1);if(e.code==='KeyR')reset();if(e.code==='KeyH'){hidden=!hidden;$('#app').classList.toggle('ui-hidden',hidden);}if(e.code==='Escape')$('#help-panel').hidden=true;if(['KeyW','KeyA','KeyS','KeyD','KeyQ','KeyE','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','ShiftLeft','Space'].includes(e.code)){e.preventDefault();keys.add(e.code);if(!e.code.startsWith('Shift')){enter();tour=null;}}});addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',()=>{keys.clear();drag=null;joystick.set(0,0);});
let drag=null;canvas.addEventListener('pointerdown',e=>{if(e.button!==0)return;drag={id:e.pointerId,x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;let dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.abs(dx)+Math.abs(dy)>0){enter();tour=null;}yaw-=dx*.0032;pitch=T.MathUtils.clamp(pitch-dy*.0028,-1.35,1.1);drag.x=e.clientX;drag.y=e.clientY;});const endDrag=()=>drag=null;canvas.addEventListener('pointerup',endDrag);canvas.addEventListener('pointercancel',endDrag);canvas.addEventListener('wheel',e=>{e.preventDefault();enter();tour=null;const fwd=new T.Vector3(-Math.sin(yaw)*Math.cos(pitch),Math.sin(pitch),-Math.cos(yaw)*Math.cos(pitch));velocity.addScaledVector(fwd,-Math.sign(e.deltaY)*5);},{passive:false});
const joystick=new T.Vector2();const stick=$('#stick'),joy=$('#joystick');let joyId=null;const moveJoy=e=>{const r=joy.getBoundingClientRect();let x=e.clientX-(r.left+r.width/2),y=e.clientY-(r.top+r.height/2);const len=Math.hypot(x,y);if(len>35){x=x/len*35;y=y/len*35;}joystick.set(x/35,y/35);stick.style.transform=`translate(${x}px,${y}px)`;};joy.addEventListener('pointerdown',e=>{enter();tour=null;joyId=e.pointerId;joy.setPointerCapture(e.pointerId);moveJoy(e);});joy.addEventListener('pointermove',e=>{if(e.pointerId===joyId)moveJoy(e);});for(let ev of ['pointerup','pointercancel'])joy.addEventListener(ev,()=>{joyId=null;joystick.set(0,0);stick.style.transform='';});for(let [id,code]of [['rise','KeyE'],['descend','KeyQ']]){const b=$('#'+id);b.addEventListener('pointerdown',e=>{enter();tour=null;b.setPointerCapture(e.pointerId);keys.add(code);});for(let ev of ['pointerup','pointercancel'])b.addEventListener(ev,()=>keys.delete(code));}
const velocity=new T.Vector3();const wish=new T.Vector3();const clock=new T.Clock();let t=0,frame=0,fpsSamples=[],resizeTimer;
function ground(x,z){let y=height(x,z);if(Math.abs(z-7)<1.8&&Math.abs(x-world.bridgeX)<7.6)y=Math.max(y,world.bridgeHeight(x)+.06);return y;}
function animate(){requestAnimationFrame(animate);if(document.hidden){clock.getDelta();return;}const rawDt=clock.getDelta();const dt=Math.min(rawDt,.05);t+=dt;frame++;world.update(t,dt);if(tour){tour.t+=dt;const f=smoother(Math.min(tour.t/3.2,1));camera.position.lerpVectors(tour.from,tour.to,f);yaw=T.MathUtils.lerp(tour.yaw0,tour.yaw1,f);pitch=T.MathUtils.lerp(tour.pitch0,tour.pitch1,f);if(tour.t>=3.2)tour=null;}else{
 const fw=(keys.has('KeyW')||keys.has('ArrowUp')?1:0)-(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-joystick.y;const side=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0)+joystick.x;const up=(keys.has('KeyE')||keys.has('Space')?1:0)-(keys.has('KeyQ')?1:0);const speed=keys.has('ShiftLeft')?15:7;wish.set(-Math.sin(yaw)*fw+Math.cos(yaw)*side,up,-Math.cos(yaw)*fw-Math.sin(yaw)*side);if(wish.lengthSq()>1)wish.normalize();if(wish.lengthSq()>0)velocity.lerp(wish.multiplyScalar(speed),1-Math.exp(-dt*7));else velocity.multiplyScalar(Math.exp(-dt*4));const old=camera.position.clone();camera.position.addScaledVector(velocity,dt);camera.position.x=T.MathUtils.clamp(camera.position.x,-112,112);camera.position.z=T.MathUtils.clamp(camera.position.z,-108,112);for(const [hx,hz,w,d,h] of homes){if(camera.position.y<height(hx,hz)+h+1.7&&Math.abs(camera.position.x-hx)<w/2+.55&&Math.abs(camera.position.z-hz)<d/2+.55){camera.position.x=old.x;camera.position.z=old.z;if(old.y>=height(hx,hz)+h+1.7){camera.position.y=old.y;velocity.y=Math.max(0,velocity.y);}velocity.x*=.15;velocity.z*=.15;}}
 camera.position.y=T.MathUtils.clamp(camera.position.y,ground(camera.position.x,camera.position.z)+1.75,75);
}camera.rotation.set(pitch,yaw,0,'YXZ');world.sky.position.copy(camera.position);renderer.info.reset();composer.render();if(frame===4){$('#loading').style.opacity='0';setTimeout(()=>$('#loading').remove(),1100);}if(frame%50===0){$('#location strong').textContent=camera.position.z<-25?'The upper village':camera.position.x<-32?'Alderwood trails':camera.position.z>24?'The wildflower meadow':'The old stone bridge';}fpsSamples.push(Math.max(.001,rawDt));if(fpsSamples.length>90)fpsSamples.shift();}
function smoother(t){return t*t*(3-2*t);}
function resize(){camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();const dpr=Math.min(devicePixelRatio,innerWidth<650?1.35:1.6,Math.sqrt(2800000/(innerWidth*innerHeight)));renderer.setPixelRatio(dpr);renderer.setSize(innerWidth,innerHeight);composer.setPixelRatio(dpr);composer.setSize(innerWidth,innerHeight);ao.setSize(Math.round(innerWidth*dpr*.6),Math.round(innerHeight*dpr*.6));grade.uniforms.resolution.value.set(innerWidth*dpr,innerHeight*dpr);fxaa.uniforms.resolution.value.set(1/(innerWidth*dpr),1/(innerHeight*dpr));}
addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(resize,90);});canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();$('#webgl-error').hidden=false;$('#webgl-error h1').textContent='The graphics session paused.';$('#webgl-error p').textContent='Reload the landscape to continue exploring.';});resize();setMode(0,false);animate();
// Nature ambience is synthesized locally and only starts after the listener opts in.
let audioCtx,gain,audioOn=false,birdTimer;
$('#sound').addEventListener('click',async()=>{if(!audioCtx){audioCtx=new(window.AudioContext||window.webkitAudioContext)();gain=audioCtx.createGain();gain.gain.value=0;gain.connect(audioCtx.destination);const b=audioCtx.createBuffer(1,audioCtx.sampleRate*4,audioCtx.sampleRate);let data=b.getChannelData(0),last=0;for(let i=0;i<data.length;i++){last=(last+.02*(Math.random()*2-1))/1.02;data[i]=last*3.4;}let src=audioCtx.createBufferSource();src.buffer=b;src.loop=true;const low=audioCtx.createBiquadFilter();low.type='lowpass';low.frequency.value=700;src.connect(low);low.connect(gain);src.start();birdTimer=setInterval(()=>{if(!audioOn)return;let now=audioCtx.currentTime;for(let i=0;i<3;i++){const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.setValueAtTime(1700+Math.random()*900,now+i*.18);o.frequency.exponentialRampToValueAtTime(3300,now+i*.18+.1);g.gain.setValueAtTime(0,now+i*.18);g.gain.linearRampToValueAtTime(.025,now+i*.18+.02);g.gain.exponentialRampToValueAtTime(.001,now+i*.18+.15);o.connect(g);g.connect(gain);o.start(now+i*.18);o.stop(now+i*.18+.16);}},6500);}await audioCtx.resume();audioOn=!audioOn;gain.gain.setTargetAtTime(audioOn?.28:0,audioCtx.currentTime,.5);$('.sound-state').textContent=audioOn?'ON':'OFF';$('#sound').setAttribute('aria-label',`Turn ${audioOn?'off':'on'} nature sounds`);});
// Read-only diagnostics and deterministic viewpoints for renderer QA.
window.__evermere={get state(){return {mode:modeNames[mode],modeIndex:mode,camera:camera.position.toArray(),rotation:[pitch,yaw],stats:world.stats,drawCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles,frames:frame,meanFPS:Math.round(fpsSamples.length/Math.max(.001,fpsSamples.reduce((a,b)=>a+b,0))),ao:ao.enabled,bloom:bloom.enabled,exploring};},setMode,reset,view(name){enter();tour=null;const views={village:[-2,4,14,-13,3,-16],bridge:[29,5.2,16,5,2,4],forest:[-43,4,31,-49,4,4],overlook:[46,24,52,-6,10,-15]};const a=views[name]||views.overlook;camera.position.set(...a.slice(0,3));camera.lookAt(...a.slice(3));yaw=camera.rotation.y;pitch=camera.rotation.x;velocity.set(0,0,0);}};
